{% set version = "1.0.0" %}
{% set linux_compiler_version = "10.4.0" %}
{% set macos_compiler_version = "16" %}

package:
  name: fierro-ls-evpfft-cpu
  version: {{ version }}

source:
  git_url: https://github.com/lanl/Fierro.git
  git_depth: 1

build:
  number: 1
  script_env:
    - PLATFORM={{ target_platform }}

requirements:
  build:
    - cmake >=3.17.0
    - make
    - {{ compiler('c') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('c') }}={{ macos_compiler_version }} # [osx]
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]
    - openmpi
  host:
    - openmpi
    - heffte-cpu
    - fftw=*=mpi_openmpi_*
    - kokkos=4.1
    - hdf5=*=mpi_openmpi_*
    - elements
  run:
    - openmpi
    - heffte-cpu
    - fftw=*=mpi_openmpi_*
    - kokkos=4.1
    - hdf5=*=mpi_openmpi_*
    - elements

about:
  home: https://github.com/lanl/Fierro
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
  description:
  dev_url: https://github.com/lanl/Fierro

extra:
  recipe-maintainers:
    - fierromechanics
