num_dims: 3
dynamic_options:
  time_final: 1.0
  dt_min: 1.e-8
  dt_max: 1.e-2
  dt_start: 1.e-5
  cycle_stop: 2

mesh_generation_options:
  type: Box
  origin: [0, 0, 0]
  length: [1.2, 1.2, 1.2]
  num_elems: [10, 10,10]

output_options:
  timer_output_level: thorough
  output_file_format: vtk
  graphics_step: 0.25
  
fea_module_parameters:
  - type: DANN
    material_id: 0
    batch_size: 1000
    training_input_data_filename: x_train.txt
    testing_input_data_filename: x_test.txt
    training_output_data_filename: y_train.txt
    testing_output_data_filename: y_test.txt

materials:
  - id: 0
    eos_model: ideal_gas
    strength_model: none
    q1: 1.0
    q2: 1.33
    q1ex: 1.0
    q2ex: 0.0
    eos_global_vars:
      - 1.666666666666667
      - 1.0E-14
      - 1.0

regions:
  - volume:
      type: global
    material_id: 0
    den: 1.0
    sie: 1.e-10
        
    velocity: cartesian
    u: 0.0
    v: 0.0
    w: 0.0
    # energy source initial conditions
  - volume:
      type: sphere
      radius1: 0.0
      radius2: 0.0375
    material_id: 0
    den: 1.0
    ie: 0.25833839995946534
        
    velocity: cartesian
    u: 0.0
    v: 0.0
    w: 0.0
