package: 
  name: evpfft_gui
  version: 1

source:
  path: ../../
  # - git_url: https://github.com/lanl/Fierro.git
  #   depth: 1

build:
  number: 2
  script: cd python/EVPFFT-GUI/; pip install .
  noarch: generic # This is a pure python package. So build for noarch on linux64
  skip: true  # [not linux64]
  skip: false # [linux64]

requirements:
  host:
    - python
    - setuptools
  run:
    - paraview=5.11.2
    - fierro-evpfft
    - fierro-voxelizer
    - python
    - pyside6

test:
  imports:
    - evpfft_gui
