{% set version = "1.0.0" %}
{% set linux_compiler_version = "10.4.0" %}
{% set macos_compiler_version = "12" %}

package: 
  name: fierro-voxelizer-py
  version: 1

source:
  path: ../../
  # - git_url: https://github.com/lanl/Fierro.git
  #   depth: 1

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('cxx') }}={{ linux_compiler_version }} # [linux]
    - {{ compiler('cxx') }}={{ macos_compiler_version }} # [osx]
  host:
    - elements
    - python
    - pybind11
    - setuptools
  run:
    - elements
    - python

test:
  imports:
    - fierro_voxelizer
