name: Build-Conda-Package

on: 
  workflow_call:
    inputs:
      recipe_dir:
        required: true
        type: string

jobs:
  build-package:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        include:
          - os: macos-latest
          # - os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "CONDA=$HOME/" >> $GITHUB_ENV
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/conda_build_environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          activate-environment: build-env
          environment-file: .etc/conda_build_environment.yaml
          condarc-file: .etc/condarc.yaml
      - run: |
          conda build ${{ inputs.recipe_dir }} -e .conda/build_variants.yaml --token ${{ secrets.ANACONDA_TOKEN }} --no-test -c kwelsh-lanl -c conda-forge -c nvidia
