name: 'Publish Fierro-dev'

on: 
  push:
    paths:
      - .conda/fierro-dev/cpu/**
      - .github/workflows/publish-fierro-dev.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/fierro-dev/cpu
    secrets: inherit
