name: 'Publish Elements'

on: 
  push:
    paths:
      - .conda/elements/**
      - .github/workflows/publish-elements.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/elements
    secrets: inherit