name: 'Publish Elements'

on: 
  push:
    paths:
      - .conda/elements/**

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: macos-latest
            variant_file: .conda/macos_build_variants.yaml
            cross_compile: 0
          - os: ubuntu-latest
            variant_file: .conda/linux_build_variants.yaml
            cross_compile: 1

    runs-on: ${{ matrix.os }}

    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/elements
      cross_compiling: ${{ matrix.cross_compile }}
      build_variant_file: ${{ matrix.variant_file }}
      os: ${{ matrix.os }}
    secrets: inherit