name: 'Publish Heffte'

on: 
  push:
    paths:
      - .conda/heffte/**
      - .github/workflows/publish-heffte-cpu.yaml

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/heffte
    secrets: inherit