name: 'Publish Voxelizer'

on: 
  push:
    paths:
      - .conda/voxelizer/**
      - src/Voxelizer/**
      - .github/workflows/publish-voxelizer.yaml

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/voxelizer
    secrets: inherit