name: 'Publish Elements-Cuda'

on: 
  push:
    paths:
      - .conda/elements/**
      - .github/workflows/publish-elements-cuda.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/elements/cuda
    secrets: inherit
