name: 'Publish Elements'

on: 
  push:
    paths:
      - .conda/elements/**

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/elements
    secrets: inherit