name: 'Publish Fierro-CPU'

on: 
  push:
    paths:
      - .conda/fierro/cpu/**
      - .github/workflows/publish-fierro-cpu.yaml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: ./.github/workflows/build-conda-package.yaml
      with:
        recipe_dir: .conda/fierro/cpu
    - name: Install MPI
      run: |
        sudo apt-get install libopenmpi-dev openmpi-bin
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      

  
