name: 'Publish Voxelizer'

on: 
  push:
    paths:
      - .conda/voxelizer/**
      - src/Voxelizer/**
      - python/Voxelizer/**
      - .github/workflows/publish-voxelizer.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/voxelizer
      additional_variant: .conda/voxelizer/python_variants.yaml
    secrets: inherit
