name: Ubuntu Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: ./configure

    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./scripts/build-fierro.sh
         ./scripts/build-fierro.sh --build_action=full-app --solver=all --kokkos_build_type=openmp --build_cores=2
      shell: bash
